### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by wesmcouch** [heremaps/gradle-jenkins-jobdsl-plugin#106]
Hello,

I am hoping to contribute to the project but I am unable to sign the CLA, it doesn't look to be responsive.

I was also wondering what formatting scheme is being used, I was hoping to use automatic formatting to match the repository code formatting because I am hitting CodeNarc errors.

**Comment by mnonnenmacher** [comment]
Hi @wesmcouch,

sorry for the late response. We use a DCO instead of a CLA, so you need to sign-off your commits. For details please see:
https://probot.github.io/apps/dco/

For formatting I usually use the default formatter from IntelliJ IDEA, plus some manual corrections in case CodeNarc fails, but we do not have a task to automatically format all code according to the CodeNarc rules.
