### ISSUE TITLE
Plugin does not work under Gradle 5.4.1

### ISSUE THREAD

**Issue by robinverduijn** [heremaps/gradle-jenkins-jobdsl-plugin#113]
I have a project that was using Gradle 4.10.3 and the gradle-jenkins-jobdsl-plugin but when I upgrade my Gradle version to 5.4.1, the command line options for e.g. `--jenkinsUrl` are no longer being recognized.

For example:

```
 + ./gradlew dslUpdateJenkins --jenkinsUrl=https:/xxx --jenkinsUser=xxx --jenkinsApiToken=xxx --dryRun

Welcome to Gradle 5.4.1!
 
 Here are the highlights of this release:
  - Run builds with JDK12
  - New API for Incremental Tasks
  - Updates to native projects, including Swift 5 support
 
 For more details see https://docs.gradle.org/5.4.1/release-notes.html

[...]

FAILURE: Build failed with an exception.
 
 * What went wrong:
 Problem configuring task :dslUpdateJenkins from command line.
 > Unknown command-line option '--jenkinsUrl'.
```

**Comment by mnonnenmacher** [comment]
Thanks for the fix @robinverduijn, I will keep this ticket open until the new release is available.

**Comment by vudzkostek** [comment]
I spent almost 2 weeks trying to find solution for this issue and couple others while upgrading gradle from 4.10.3 to 5.x. This issue is the only thing that is left and I am glad I am not the only one :)

I get:
FAILURE: Build failed with an exception.

* What went wrong:
Problem configuring task :jobdsl:dslGenerateXml from command line.
> Unknown command-line option '--server'.

We do use very old version of plugin 1.0.32 but I also checked with 3.4.0 and same issue.

@mnonnenmacher you can also test it on your own as we still work in same company :)

**Comment by mnonnenmacher** [comment]
I just release version 3.5.0, please reopen this ticket if it does not fix the issue for you.

**Comment by vudzkostek** [comment]
I can confirm that it works for me now
