### ISSUE TITLE
failed when use  Third-party libraries in jobdsl 

### ISSUE THREAD

**Issue by jiahut** [heremaps/gradle-jenkins-jobdsl-plugin#89]
We need fetch some config from server before generate job , so we add the the third-party http library with blew: 

`   compile 'io.github.http-builder-ng:http-builder-ng-core:1.0.3'`

but it failed when execute `dslUpdateJenkins`

at present  we use 

```
def p = ['curl', "http://localhost:8080/config/api"].execute()
def json = new JsonSlurper().parseText(p.text)
```
as an alternative .

does `jobdsl-plugin` can <b>not</b> use  Third-party libraries ?

**Comment by jiahut** [comment]
Thank you for your prompt reply.  👍 

the `HttpTool` source code blew: 
```
class HttpTool {
   static getConfig(String token) {
        def http = configure {
            request.uri = "http://localhost:8080"
        }

        def json = http.get {
            request.uri.path = '/config/api'
            response.parser('application/json') { cc, fs ->
                new JsonSlurper().parse(fs.inputStream)
            }
        }
        return json.data
  }
} 
```

> gradle -b jenkins5.gradle dslUpdateJenkins --server=my-jenkins

```
> Configure project :
[status:SUCCESS, data:[name:devops-ding, gitCredentials:ac88890c-c9d3-4bd8-8b08-31f1831910c8, gitBranch:master]]

> Task :dslUpdateJenkins
Using server configuration 'jenkinsT'
=== Starting Run Job DSL Task
Installed plugins: [build-timeout:1.18, structs:1.9, token-macro:1.5.1, job-dsl:1.67, script-security:1.25]
Remote Jenkins is version 2.121.1
Loading /Users/jiahut/develop/auto-deploy/src/demo/demoJobs.groovy
Processing provided DSL script


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dslUpdateJenkins'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 9s
4 actionable tasks: 1 executed, 3 up-to-date
```

**Comment by mnonnenmacher** [comment]
I saw this error before when there are classpath issues, unfortunately I couldn't get better output in this case because the JVM just crashes. Looking at the library you use most likely the problem is that the plugin itself dependes on `org.codehaus.groovy.modules.http-builder:http-builder:0.7.2` which partly contains the same classes as `io.github.http-builder-ng:http-builder-ng-core:1.0.3`. This means depending on the order these libraries appear on the classpath the wrong version of these classes could be loaded which crashes the JVM.
You could try to use `http-builder` instead, I think for your use case of downloading a file it should be good enough. Or mabye you don't need a library and this would be good enough: http://groovy-almanac.org/save-url-to-file/

**Comment by jiahut** [comment]
thinks @mnonnenmacher ，you are right,  rewrite it  use  `http-builder` , it does well.

**Comment by mnonnenmacher** [comment]
@jiahut Thanks for the feedback, I will close the ticket.
